services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/shortener.db:/app/shortener.db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - fileName
    depends_on:
      - backend
    restart: always